### ISSUE TITLE
Mixed tabs and Space.

### ISSUE THREAD

**Issue by Carreau** [grumpfou/RFigure#3]
Some files have mixed tabs and space, this should likely be updated. 

I would recommend running [black](https://github.com/ambv/black) on the project. It reformat everything and has no configuration options. It's controversial; but at least there is no disagreament on the formatting.

**Comment by grumpfou** [comment]
Thanks. I  normally changed all the files to use tabs. I will have a better look into **black** to see if it would be a good thing.
